version: 2

jobs:
    build:
      machine:
        docker_layer_caching: true
      steps:
        - checkout
        - run:
            name: Build Docker image
            command: docker-compose build

    test:
      machine:
        docker_layer_caching: true
      steps:
        - checkout
        - run:
            name: Start containers
            command: |
              docker-compose up -d
              docker-compose exec web bundle exec rails db:create
              docker-compose exec web bundle exec rails db:migrate
              docker-compose exec web bundle exec rspec

    touch-hello:
      docker:
        - image: cimg/ruby:2.7-node
      steps:
        - checkout
        - run:
            name: Touch file
            command: |
              touch hello.txt
              exit 1

    touch-bye:
      docker:
        - image: cimg/ruby:2.7-node
      steps:
        - checkout
        - run:
            name: Touch file
            command: |
              touch bye.txt
              ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - touch-hello
      - touch-bye:
          requires:
            - touch-hello
