version: 2

jobs:
    build:
      machine:
        docker_layer_caching: true
      steps:
        - checkout
        - run:
            name: Build Docker image
            command: docker-compose build

    test:
      machine:
        docker_layer_caching: true
      steps:
        - checkout
        - run:
            name: Start containers
            command: |
              docker-compose up -d
              docker-compose exec web bundle exec rails db:migrate
              docker-compose exec web bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
