version: 2

jobs:
    build:
      docker:
        - image: circleci/buildpack-deps 
      steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
        - run:
            name: Build Docker image
            command: docker-compose build

    test:
      docker:
        - image: circleci/buildpack-deps
      steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: true
        - run:
            name: Start containers
            command: |
              docker-compose up -d
        - run:
            name: Run RSpec
            command: |
              docker-compose exec web bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
